on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 16
          cache: 'npm'
      - run: sudo xcode-select -s /Applications/Xcode_26.0.1.app/Contents/Developer
      - run: npm ci
      - run: scripts/ensure_generated_files_are_up_to_date.sh
      - run: scripts/run_tests.sh
      - run: scripts/build_app.sh
