on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 16
          cache: 'npm'
      - run: sudo xcode-select -s /Applications/Xcode_26.0.1.app/Contents/Developer
      - run: npm ci
      - run: scripts/ensure_generated_files_are_up_to_date.sh
      - run: scripts/run_tests.sh
      - run: |
          set -o pipefail
          xcodebuild -project alt-tab-macos.xcodeproj -scheme Release -derivedDataPath DerivedData CODE_SIGN_IDENTITY="-" CODE_SIGNING_REQUIRED=YES | scripts/xcbeautify
      - name: Package
        run: |
          APP_PATH="DerivedData/Build/Products/Release/AltTab.app"
          ZIP_NAME="AltTab-${{ github.ref_name }}.zip"
          ditto -c -k --keepParent "$APP_PATH" "$ZIP_NAME"
          echo "zip_name=$ZIP_NAME" >> "$GITHUB_OUTPUT"
          echo "is_tag=${{ startsWith(github.ref, 'refs/tags/') }}" >> "$GITHUB_OUTPUT"
        id: package
      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "AltTab ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }}"
          files: ${{ steps.package.outputs.zip_name }}
